import { useEffect, useMemo, useRef, useState } from "react";
import { recommendOutfit, twinProfileSchema, validateProfileInput, type BodyMeasurements, type StylePreferences, type TwinProfile, type WardrobeCategory, type WardrobeItem } from "@fittwin/core";
import { TwinSilhouette, twinSilhouetteCss } from "@fittwin/react";
import { createFitTwin, DeterministicStyleAdvisor, type StyleAdvisor, type StyleGuide } from "@fittwin/sdk";
import { decryptProfile, encryptProfile, type EncryptedBackup } from "./backup";
import { IndexedDbProfileStore, IndexedDbWardrobeStore } from "./store";

const PROFILE_ID = "personal-profile";
const defaults: BodyMeasurements = { height: { value: 170, unit: "cm" }, shoulder: { value: 42, unit: "cm" }, chest: { value: 90, unit: "cm" }, waist: { value: 74, unit: "cm" }, hip: { value: 96, unit: "cm" }, inseam: { value: 78, unit: "cm" } };
const defaultPreferences: StylePreferences = { goals: ["minimal"], occasions: ["daily"], fitPreference: "regular", avoid: [] };
const measurementKeys = ["height", "shoulder", "chest", "waist", "hip", "inseam", "torso", "arm", "thigh"] as Array<keyof BodyMeasurements>;
const optionalKeys = new Set(["torso", "arm", "thigh"]);
const categories: WardrobeCategory[] = ["top", "bottom", "outerwear", "dress", "shoes", "accessory"];
const labels = {
  zh: { intro: "你的本地身材档案与穿衣指南", language: "EN", measurements: "身体测量", preferences: "风格偏好", create: "保存我的档案", saved: "档案已保存在此设备", twin: "中性数字孪生", insights: "比例观察", quickGuide: "基础穿衣报告", quickGuideNote: "无需账号、模型 Key 或网络连接。", getQuickGuide: "立即生成基础报告", ai: "更细致的 AI 指南", copyCommand: "复制启动 companion 命令", consent: "我同意仅将本次所需的匿名化身材摘要和偏好发送到我自己的本地代理。", generate: "生成 AI 指南", endpoint: "本地代理地址", token: "配对令牌", wardrobe: "我的衣柜", addItem: "加入衣柜", itemName: "衣物名称", itemCategory: "类别", color: "颜色", outfit: "今日搭配", temperature: "气温", remove: "移除", feedback: "这条建议对我有用", notUseful: "不适合我", export: "导出 JSON", encrypted: "加密备份", import: "导入备份", password: "备份密码（至少 10 位）", erase: "删除本机数据", privacy: "默认不联网，不收集遥测，不保存 API Key。", height: "身高", shoulder: "肩宽", chest: "胸围", waist: "腰围", hip: "臀围", inseam: "内侧裤长", torso: "躯干长度（可选）", arm: "臂长（可选）", thigh: "大腿围（可选）", goals: "想呈现的风格", occasions: "常见场景", fit: "合身偏好", avoid: "想避开的元素（用逗号分隔）", measurementTips: ["穿着贴身衣物，保持自然站姿。", "软尺应贴合身体，不要刻意收紧或留太多空隙。", "不确定时记录两次，取平均值。"] },
  en: { intro: "Your private body profile and style guide", language: "中文", measurements: "Measurements", preferences: "Style preferences", create: "Save my profile", saved: "Profile saved on this device", twin: "Neutral digital twin", insights: "Proportion notes", quickGuide: "Instant base guide", quickGuideNote: "No account, provider key, or network request required.", getQuickGuide: "Generate base guide", ai: "More detailed AI guide", copyCommand: "Copy companion command", consent: "I agree to send only this request's minimized body summary and preferences to my own local companion.", generate: "Generate AI guide", endpoint: "Local companion URL", token: "Pairing token", wardrobe: "My wardrobe", addItem: "Add item", itemName: "Item name", itemCategory: "Category", color: "Color", outfit: "Today's outfit", temperature: "Temperature", remove: "Remove", feedback: "This helps", notUseful: "Not for me", export: "Export JSON", encrypted: "Encrypted backup", import: "Import backup", password: "Backup password (10+ characters)", erase: "Delete local data", privacy: "No network by default, no telemetry, no stored API keys.", height: "Height", shoulder: "Shoulder width", chest: "Chest", waist: "Waist", hip: "Hip", inseam: "Inseam", torso: "Torso length (optional)", arm: "Arm length (optional)", thigh: "Thigh circumference (optional)", goals: "Style goals", occasions: "Typical occasions", fit: "Fit preference", avoid: "Avoid (comma separated)", measurementTips: ["Wear close-fitting clothing and stand naturally.", "Keep the tape close to the body without tightening it.", "If unsure, measure twice and use the average."] }
} as const;

class LocalCompanionAdvisor implements StyleAdvisor {
  constructor(private endpoint: string, private token: string) {}
  async generate(input: Parameters<StyleAdvisor["generate"]>[0]): Promise<StyleGuide> {
    const response = await fetch(`${this.endpoint.replace(/\/$/, "")}/v1/style-guide`, { method: "POST", headers: { "content-type": "application/json", "x-fittwin-token": this.token }, body: JSON.stringify({ measurements: input.measurements, preferences: input.preferences, feedback: input.feedback }) });
    if (!response.ok) throw new Error(await response.text() || `Local companion returned ${response.status}`);
    return response.json() as Promise<StyleGuide>;
  }
}

export function App() {
  const [language, setLanguage] = useState<"zh" | "en">("zh");
  const [measurements, setMeasurements] = useState<BodyMeasurements>(defaults);
  const [preferences, setPreferences] = useState<StylePreferences>(defaultPreferences);
  const [profile, setProfile] = useState<TwinProfile>();
  const [guide, setGuide] = useState<StyleGuide>();
  const [wardrobe, setWardrobe] = useState<WardrobeItem[]>([]);
  const [itemName, setItemName] = useState("");
  const [itemCategory, setItemCategory] = useState<WardrobeCategory>("top");
  const [itemColor, setItemColor] = useState("neutral");
  const [temperature, setTemperature] = useState(20);
  const [consent, setConsent] = useState(false);
  const [endpoint, setEndpoint] = useState("http://127.0.0.1:47831");
  const [token, setToken] = useState("");
  const [password, setPassword] = useState("");
  const [status, setStatus] = useState<string>();
  const importRef = useRef<HTMLInputElement>(null);
  const t = labels[language];
  const profileStore = useMemo(() => new IndexedDbProfileStore(), []);
  const wardrobeStore = useMemo(() => new IndexedDbWardrobeStore(), []);
  const sdk = useMemo(() => createFitTwin({ store: profileStore }), [profileStore]);

  useEffect(() => { Promise.all([sdk.getProfile(PROFILE_ID), wardrobeStore.list()]).then(([saved, items]) => { if (saved) { setProfile(saved); setMeasurements(saved.measurements); setPreferences(saved.preferences); } setWardrobe(items); }).catch(() => setStatus("Unable to read local storage.")); }, [sdk, wardrobeStore]);

  const currentProfile = async () => {
    const warnings = validateProfileInput(measurements);
    if (warnings.length) throw new Error(warnings.join(" "));
    const updated = profile ? await sdk.updateProfile(PROFILE_ID, { measurements, preferences }) : await sdk.createProfile({ id: PROFILE_ID, measurements, preferences });
    setProfile(updated); return updated;
  };
  const save = async () => { try { await currentProfile(); setStatus(t.saved); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to save profile."); } };
  const generateOffline = async () => { try { await currentProfile(); const offlineSdk = createFitTwin({ store: profileStore, advisor: new DeterministicStyleAdvisor() }); setGuide(await offlineSdk.generateStyleGuide(PROFILE_ID)); setStatus(language === "zh" ? "基础报告已在本机生成。" : "Base guide generated locally."); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to generate guide."); } };
  const generateAi = async () => { if (!consent) return setStatus(t.consent); try { await currentProfile(); const aiSdk = createFitTwin({ store: profileStore, advisor: new LocalCompanionAdvisor(endpoint, token) }); setGuide(await aiSdk.generateStyleGuide(PROFILE_ID)); setStatus(language === "zh" ? "已从你的本地 companion 收到指南。" : "Guide received from your local companion."); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to generate guide."); } };
  const feedback = async (sentiment: "like" | "dislike") => { if (!profile) return; const trait = guide?.silhouettes[0]?.recommendation ?? "style guide"; const updated = await sdk.updateProfile(PROFILE_ID, { feedback: [...profile.feedback, { trait, sentiment, createdAt: new Date().toISOString() }] }); setProfile(updated); setStatus(language === "zh" ? "反馈已仅保存在本机。" : "Feedback saved locally."); };
  const addWardrobeItem = async (event: React.FormEvent) => { event.preventDefault(); if (!itemName.trim()) return; const item: WardrobeItem = { id: crypto.randomUUID(), name: itemName.trim(), category: itemCategory, color: itemColor.trim() || "neutral", formality: preferences.occasions.includes("work") ? 4 : 3, warmth: 3, styleTags: preferences.goals.slice(0, 2), createdAt: new Date().toISOString() }; await wardrobeStore.set(item); setWardrobe((items) => [...items, item]); setItemName(""); };
  const removeWardrobeItem = async (id: string) => { await wardrobeStore.remove(id); setWardrobe((items) => items.filter((item) => item.id !== id)); };
  const exportProfile = async (encrypted = false) => { if (!profile) return; try { const data = encrypted ? await encryptProfile(profile, password) : profile; download(data, encrypted ? "fittwin-backup.encrypted.json" : "fittwin-profile.json"); setStatus(encrypted ? (language === "zh" ? "加密备份已下载。" : "Encrypted backup downloaded.") : (language === "zh" ? "档案已导出。" : "Profile exported.")); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to export backup."); } };
  const importProfile = async (file: File) => { try { const raw = JSON.parse(await file.text()) as TwinProfile | EncryptedBackup; const imported = "ciphertext" in raw ? await decryptProfile(raw, password) : twinProfileSchema.parse(raw); const local = { ...imported, id: PROFILE_ID, updatedAt: new Date().toISOString() }; await profileStore.set(local); setProfile(local); setMeasurements(local.measurements); setPreferences(local.preferences); setGuide(undefined); setStatus(language === "zh" ? "档案已导入到此设备。" : "Profile imported to this device."); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to import backup."); } };
  const erase = async () => { await profileStore.clear(); await wardrobeStore.clear(); setProfile(undefined); setGuide(undefined); setWardrobe([]); setStatus(language === "zh" ? "本机档案与衣柜已删除。" : "Local profile and wardrobe deleted."); };
  const copyCompanionCommand = async () => { await navigator.clipboard.writeText("pnpm dev:companion"); setStatus(language === "zh" ? "已复制命令：pnpm dev:companion" : "Copied: pnpm dev:companion"); };
  const setMeasurement = (key: keyof BodyMeasurements, value: string) => setMeasurements((current) => ({ ...current, [key]: value ? { value: Number(value), unit: current[key]?.unit ?? "cm" } : undefined }));
  const outfit = profile ? recommendOutfit(profile, wardrobe, { occasion: preferences.occasions[0], temperatureC: temperature }) : undefined;

  return <main><style>{twinSilhouetteCss}</style><header><div><strong>FitTwin</strong><span>{t.intro}</span></div><button className="text-button" onClick={() => setLanguage(language === "zh" ? "en" : "zh")}>{t.language}</button></header>
    <section className="hero"><p className="eyebrow">PRIVATE BY DEFAULT</p><h1>Fit that starts<br /><em>with you.</em></h1><p>{t.privacy}</p></section>
    <section className="workspace"><form className="profile-form" onSubmit={(event) => { event.preventDefault(); void save(); }}><div className="section-heading"><h2>{t.measurements}</h2><span>cm / in</span></div><details className="tips"><summary>{language === "zh" ? "如何测量" : "How to measure"}</summary><ol>{t.measurementTips.map((tip) => <li key={tip}>{tip}</li>)}</ol></details><div className="measure-grid">{measurementKeys.map((key) => <label key={key}>{t[key]}<div className="measurement-input"><input required={!optionalKeys.has(key)} min="1" type="number" value={measurements[key]?.value ?? ""} onChange={(event) => setMeasurement(key, event.target.value)} /><select value={measurements[key]?.unit ?? "cm"} onChange={(event) => setMeasurements((current) => ({ ...current, [key]: { value: current[key]?.value ?? 0, unit: event.target.value as "cm" | "in" } }))}><option>cm</option><option>in</option></select></div></label>)}</div><div className="section-heading space"><h2>{t.preferences}</h2></div><fieldset><legend>{t.goals}</legend><div className="chip-row">{["minimal", "classic", "streetwear", "creative", "sport", "formal"].map((goal) => <button type="button" key={goal} className={preferences.goals.includes(goal as never) ? "chip active" : "chip"} onClick={() => setPreferences((p) => ({ ...p, goals: p.goals.includes(goal as never) && p.goals.length > 1 ? p.goals.filter((item) => item !== goal) as StylePreferences["goals"] : p.goals.includes(goal as never) ? p.goals : [...p.goals, goal as never] }))}>{goal}</button>)}</div></fieldset><fieldset><legend>{t.occasions}</legend><div className="chip-row">{["daily", "work", "date", "travel", "event"].map((occasion) => <button type="button" key={occasion} className={preferences.occasions.includes(occasion as never) ? "chip active" : "chip"} onClick={() => setPreferences((p) => ({ ...p, occasions: p.occasions.includes(occasion as never) && p.occasions.length > 1 ? p.occasions.filter((item) => item !== occasion) as StylePreferences["occasions"] : p.occasions.includes(occasion as never) ? p.occasions : [...p.occasions, occasion as never] }))}>{occasion}</button>)}</div></fieldset><label>{t.fit}<select className="wide" value={preferences.fitPreference} onChange={(event) => setPreferences((p) => ({ ...p, fitPreference: event.target.value as StylePreferences["fitPreference"] }))}><option value="slim">slim</option><option value="regular">regular</option><option value="relaxed">relaxed</option></select></label><label>{t.avoid}<input value={preferences.avoid.join(", ")} onChange={(event) => setPreferences((p) => ({ ...p, avoid: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) }))} /></label><button className="primary" type="submit">{t.create}</button></form>
      <aside className="twin-panel"><div className="section-heading"><h2>{t.twin}</h2><span>v1.1</span></div><TwinSilhouette measurements={measurements} /><div className="insights"><h3>{t.insights}</h3>{profile ? <ul>{profile && twinNotes(measurements, language).map((note) => <li key={note}>{note}</li>)}</ul> : <p>{language === "zh" ? "保存档案后会保留你的比例观察。" : "Save a profile to retain your notes."}</p>}</div></aside></section>
    <section className="guide-start"><div><p className="eyebrow">NO KEY NEEDED</p><h2>{t.quickGuide}</h2><p>{t.quickGuideNote}</p></div><button className="primary" onClick={() => void generateOffline()}>{t.getQuickGuide}</button></section>
    <section className="ai-section"><div><p className="eyebrow">LOCAL COMPANION</p><h2>{t.ai}</h2><button className="text-button" onClick={() => void copyCompanionCommand()}>{t.copyCommand}</button></div><div className="ai-control"><label>{t.endpoint}<input value={endpoint} onChange={(event) => setEndpoint(event.target.value)} /></label><label>{t.token}<input value={token} onChange={(event) => setToken(event.target.value)} type="password" autoComplete="off" /></label><label className="consent"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} />{t.consent}</label><button className="primary" onClick={() => void generateAi()} disabled={!token}>{t.generate}</button></div></section>
    <section className="wardrobe"><div className="section-heading"><h2>{t.wardrobe}</h2><span>{wardrobe.length}</span></div><form className="wardrobe-form" onSubmit={(event) => void addWardrobeItem(event)}><label>{t.itemName}<input value={itemName} onChange={(event) => setItemName(event.target.value)} /></label><label>{t.itemCategory}<select value={itemCategory} onChange={(event) => setItemCategory(event.target.value as WardrobeCategory)}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>{t.color}<input value={itemColor} onChange={(event) => setItemColor(event.target.value)} /></label><button className="primary" type="submit">{t.addItem}</button></form><div className="wardrobe-list">{wardrobe.map((item) => <article key={item.id}><strong>{item.name}</strong><span>{item.category} · {item.color}</span><button className="text-button" onClick={() => void removeWardrobeItem(item.id)}>{t.remove}</button></article>)}{!wardrobe.length && <p>{language === "zh" ? "先加入几件常穿衣物，搭配建议只会使用你的衣柜。" : "Add a few pieces; recommendations only use your own wardrobe."}</p>}</div><div className="outfit"><div><h3>{t.outfit}</h3><label>{t.temperature}<input type="number" value={temperature} onChange={(event) => setTemperature(Number(event.target.value))} /> °C</label></div>{outfit && <p>{outfit.reason}</p>}</div></section>
    {guide && <section className="guide"><div className="guide-intro"><p className="eyebrow">YOUR GUIDE</p><h2>{guide.summary}</h2><p>{guide.careNote}</p></div><div className="guide-content"><h3>{language === "zh" ? "建议" : "Advice"}</h3>{guide.silhouettes.map((item) => <article key={item.recommendation}><strong>{item.recommendation}</strong><p>{item.reason}</p></article>)}<h3>{language === "zh" ? "搭配公式" : "Outfit formulas"}</h3>{guide.outfitRecipes.map((item) => <article key={item.formula}><strong>{item.occasion}</strong><p>{item.formula} — {item.reason}</p></article>)}<div className="feedback"><button className="chip" onClick={() => void feedback("like")}>{t.feedback}</button><button className="chip" onClick={() => void feedback("dislike")}>{t.notUseful}</button></div></div></section>}
    <footer>{status && <p role="status">{status}</p>}<div className="backup-actions"><label>{t.password}<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /></label><button className="text-button" onClick={() => void exportProfile()} disabled={!profile}>{t.export}</button><button className="text-button" onClick={() => void exportProfile(true)} disabled={!profile}>{t.encrypted}</button><button className="text-button" onClick={() => importRef.current?.click()}>{t.import}</button><input ref={importRef} hidden type="file" accept="application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importProfile(file); event.currentTarget.value = ""; }} /><button className="text-button danger" onClick={() => void erase()}>{t.erase}</button></div></footer>
  </main>;
}

function download(data: unknown, name: string) { const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
function twinNotes(measurements: BodyMeasurements, language: "zh" | "en") { const ratio = measurements.shoulder.value / measurements.hip.value; const legs = measurements.inseam.value / measurements.height.value; if (language === "en") return [ratio >= .94 ? "Your shoulder and hip widths read as balanced." : "Your lower half reads visually wider than your shoulder line.", measurements.waist.value / measurements.hip.value <= .8 ? "A defined waist can be highlighted when that feels like your style." : "Straight or softly structured layers can create a clean vertical line.", legs >= .45 ? "Longer-looking leg proportions work well with cropped or tucked tops." : "Higher rises and a consistent trouser break can lengthen the visual line."]; return [ratio >= .94 ? "肩线和臀部比例整体较均衡。" : "下半身在视觉上比肩线更宽一些。", measurements.waist.value / measurements.hip.value <= .8 ? "如果符合你的风格，可以用腰线强调来增加层次。" : "直线条或柔和结构感的叠穿能形成干净的纵向线条。", legs >= .45 ? "短款或扎进下装的上衣能突出腿部比例。" : "高腰线和连贯的裤装线条能拉长视觉比例。"]; }
